# Generated by Django 3.2.16 on 2022-11-17 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDKList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=50, null=True)),
                ('Keywords', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contentlist',
            name='Alt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentlist',
            name='BlockName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentlist',
            name='Content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentlist',
            name='Title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
