# Generated by Django 3.2.16 on 2023-01-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanage', '0003_auto_20221118_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='Content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tdklist',
            name='Description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
