# Generated by Django 3.2.16 on 2022-10-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogList',
            fields=[
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Catego', models.CharField(max_length=10)),
                ('Tag', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=20)),
                ('Content', models.TextField()),
                ('PubTime', models.DateTimeField(auto_now=True)),
                ('Enable', models.BooleanField(default=False)),
                ('Press', models.IntegerField(default=0)),
                ('Like', models.IntegerField(default=0)),
            ],
        ),
    ]
