# Generated by Django 3.2.16 on 2022-10-11 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
