# Generated by Django 3.2.16 on 2022-11-17 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloglist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='Catego',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='Content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='Desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='Tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
